[package]
name = "rai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llm = { git = "https://github.com/rustformers/llm.git", branch = "main" }
dotenv = "0.15.0"
rand = "0.8.5"
